# Generated by Django 3.2.5 on 2022-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcp_sno', models.IntegerField()),
                ('ckg_nm', models.TextField()),
                ('inq_cnt', models.IntegerField()),
                ('rcmm_cnt', models.IntegerField()),
                ('ckg_mth_acto_nm', models.TextField()),
                ('ckg_sta_acto_nm', models.TextField()),
                ('ckg_mtrl_acto_nm', models.TextField()),
                ('ckg_knd_acto_nm', models.TextField()),
                ('ckg_mtrl_cn', models.TextField()),
                ('ckg_time_nm', models.TextField()),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
    ]
