# Generated by Django 3.2.5 on 2022-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user_ref',
                'managed': False,
            },
        ),
    ]
