# Generated by Django 3.2.5 on 2022-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_userref'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
            ],
            options={
                'db_table': 'check',
                'managed': False,
            },
        ),
    ]
