# Generated by Django 3.2.5 on 2022-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0003_usercheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('board_title', models.CharField(max_length=50)),
                ('board_contents', models.TextField()),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
