# Generated by Django 3.2.5 on 2022-01-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercheck',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userref',
            options={},
        ),
    ]
