# Generated by Django 3.2.5 on 2022-01-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_auto_20220124_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usercheck',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userref',
            options={'managed': False},
        ),
    ]
