# Generated by Django 3.2.5 on 2022-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0006_auto_20220124_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('board_id', models.IntegerField()),
            ],
            options={
                'db_table': 'check',
                'managed': False,
            },
        ),
    ]
