<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.5 on 2022-01-24 07:10
=======
# Generated by Django 3.2.5 on 2022-01-24 04:47
>>>>>>> ingre_ui
=======
# Generated by Django 3.2.5 on 2022-01-24 05:29
>>>>>>> comm

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0007_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
