# Generated by Django 3.2.5 on 2022-01-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0007_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
