# Generated by Django 3.2.5 on 2022-01-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0008_delete_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercheck',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userref',
            options={},
        ),
    ]
