# Generated by Django 3.2.5 on 2022-01-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ref', '0009_auto_20220124_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(null=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCheck',
        ),
        migrations.DeleteModel(
            name='UserRef',
        ),
        migrations.AddField(
            model_name='board',
            name='rcp_sno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ref.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inq_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rcmm_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='board',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
