# Generated by Django 3.2.5 on 2022-01-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0010_auto_20220125_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mtrl',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mtrl_cnt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rcp_sno',
            field=models.IntegerField(default=0),
        ),
    ]
