# Generated by Django 3.2.5 on 2022-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0011_auto_20220126_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rcp_sno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
