# Generated by Django 3.2.5 on 2022-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('contents', models.TextField()),
                ('views', models.IntegerField()),
                ('regdate', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('write_id', models.CharField(max_length=45)),
                ('post_like_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Community_Board',
        ),
    ]
