# Generated by Django 3.2.5 on 2022-01-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220124_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
